Fix release steps/rules
fibercrypto/skywallet-mcu pull request #366
Opened 2019-11-18 18:14 UTC by stdevAlDen

Fixes #365 

Changes:	
- Fix release instructions

Does this change need to mentioned in CHANGELOG.md?	
no	

Requires testing	
no

2019-11-20 18:26 UTC, olemis requested changes

2019-11-20 18:26 UTC, olemis commented on Makefile
> +	cp combined.bin ../../../releases/skywallet-full-mem-protect-$(COMBINED_VERSION).bin
Parameterize `../../../releases` in global `RELEASE_PATH` variable.

2019-11-20 20:29 UTC, stdevAlDen commented on .travis.yml
> +    secure: TODO generate it using travis CLI
@olemis fill this pls

2019-11-20 20:29 UTC, stdevAlDen commented on .travis.yml
> +    secure: TODO generate it using travis CLI
@olemis fill this pls

2019-11-21 20:36 UTC, olemis requested changes

2019-11-21 20:36 UTC, olemis commented on README.md
>  **Note**: This repo is no longer maintained. Please refer to the new [Skywallet](https://github.com/SkycoinProject/hardware-wallet) repo.
@stdevAlDen remove this line .

2019-11-22 07:13 UTC, olemis approved these changes

2019-11-22 07:14 UTC, merged